Repository DEV-TINO/PLAY-TINO-FE, pull requests merged in 2024-06, with the labels that each got.

#54 feat : prevent getting comments after click heart, fix pagination error, make userName shorter
  src/components/CommentPage.vue
  src/components/QuizStatisticPage.vue
  src/components/TimerStatisticPage.vue
Labels: enhancement

#48 feat: main, favorite, statistic page mobile responsive design and fix favorite page final round error
  src/components/FavoriteFinishModal.vue
  src/components/FavoritePage.vue
  src/components/FavoriteStatisticPage.vue
  src/components/MainPage.vue
  src/components/QuizStatisticPage.vue
  src/components/TimerStatisticPage.vue
  tailwind.config.js
Labels: bug, enhancement

#57 fix: Quiz table mobile design
  src/components/QuizStatisticPage.vue
  tailwind.config.js
Labels: bug

#58 fix: quiz table error
  src/components/QuizStatisticPage.vue
Labels: bug

#60 fix: header design and login error
  src/components/FavoriteStatisticPage.vue
  src/components/MainPage.vue
  src/components/QuizStatisticPage.vue
  src/components/TimerStatisticPage.vue
Labels: bug

#61 fix : statistic page alignment
  src/components/QuizStatisticPage.vue
  src/components/TimerStatisticPage.vue
Labels: bug

#62 fix: timer table mobile design and change api host address
  src/components/QuizPage.vue
  src/components/TimerStatisticPage.vue
  src/store.js
Labels: bug, enhancement

#63 fix : fix reload issue
  src/App.vue
Labels: bug

#64 fix : fix reload issue
  src/App.vue
Labels: bug

#66 feat : statistic page alignment
  src/components/TimerStatisticPage.vue
Labels: enhancement

#68 fix: favorite page responsitive design error
  tailwind.config.js
Labels: bug
