Repository DEV-TINO/PLAY-TINO-FE, pull requests merged in 2024-05, with the labels that each got.

#10 fix: file recovery
  package-lock.json
  src/components/FavoritePage.vue
  src/components/FavoriteStatisticPage.vue
  src/store.js
  tailwind.config.js
  tatus
Labels: help wanted

#12 refactor: favorite page image pair rendering, favorite statistic page style
  src/components/FavoritePage.vue
  src/components/FavoriteStatisticPage.vue
  src/store.js
Labels: enhancement

#13 fix: favorite page image disable error
  src/components/FavoritePage.vue
  src/store.js
Labels: enhancement

#15 feat : server url updated
  src/store.js
Labels: enhancement

#23 fix: block user drag, use tailwind select
  src/components/FavoritePage.vue
  src/components/FavoriteStatisticPage.vue
  src/components/MainPage.vue
Labels: bug

#29 Fix : block dragging
  src/components/CommentPage.vue
  src/components/QuizCorrectModal.vue
  src/components/QuizPage.vue
  src/components/QuizResultModal.vue
  src/components/QuizStatisticPage.vue
  src/components/QuizWrongModal.vue
  src/components/TimerPage.vue
  src/components/TimerResultModal.vue
  src/components/TimerStatisticPage.vue
Labels: bug

#30 fix: favorite statistic page data error
  src/components/FavoriteStatisticPage.vue
  src/store.js
Labels: bug

#32 feat : login
  src/App.vue
  src/components/MainPage.vue
  src/store.js
Labels: enhancement

#37 fix : game replay not working
  src/components/FavoritePage.vue
  src/components/QuizPage.vue
  src/components/QuizResultModal.vue
  src/components/TimerPage.vue
  src/components/TimerResultModal.vue
Labels: bug

#39 feat : make confirmation before delete comment
  src/components/CommentPage.vue
Labels: enhancement

#41 fix: get favorite data error
  src/components/FavoritePage.vue
Labels: bug

#42 feat : change to responsive design of quiz, timer page and modals
  src/components/FavoriteFinishModal.vue
  src/components/QuizCorrectModal.vue
  src/components/QuizPage.vue
  src/components/QuizResultModal.vue
  src/components/QuizWrongModal.vue
  src/components/TimerPage.vue
  src/components/TimerResultModal.vue
Labels: enhancement

#43 fix: favorite statistic page persent bar error
  src/assets/css/errorImage.png
  src/components/FavoriteStatisticPage.vue
  src/store.js
Labels: bug

#45 fix: favorite page image loading error, use skeleton animation
  src/assets/css/errorImage.png
  src/components/FavoritePage.vue
  src/components/FavoriteStatisticPage.vue
  src/components/MainPage.vue
  src/store.js
Labels: enhancement

#50 feat : display by user name
  src/components/CommentPage.vue
  src/components/QuizStatisticPage.vue
  src/components/TimerStatisticPage.vue
Labels: enhancement

#51 feat : display top 100 rankings and change result modal text depend on ranking
  src/components/QuizPage.vue
  src/components/QuizResultModal.vue
  src/components/TimerPage.vue
  src/components/TimerResultModal.vue
Labels: enhancement
